# -*- coding: utf-8 -*-
"""stackimp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ADZ1l6YmVhTB6YX_FtmroxQ256Ta0n7d
"""

stack = []
n = int(input('Enter stack size '))
p = n
while n!=0:
  k = int(input('enter element '))
  stack.append(k)
  n-=1
print('initial stack')
print(stack)
x = int(input('enter number of elements to pop '))
if(x>p):
  print('you entered stack size as '+str(p)+' which is less then elements to pop')
else:
  while x!=0: 
    stack.pop()
    x-=1
print('stack after deletion')    
print(stack)

